name: Cargo test CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the source
        uses: actions/checkout@v3
      - name: Run `cargo test`
        uses: icepuma/rust-action@master
        with:
          args: cargo test
